@startuml
|客户端|
start
:请求天气信息;
|服务端|
if (是否输入地点) then (否)
  :根据IP获取地点;
else (是)
    if (地点是否正确) then (否)
        :根据IP获取地点;
    endif
endif

|数据库|
:查询该地点缓存信息;
|服务端|
if (缓存是否失效) then (失效)
|气象服务|
   :获取天气信息;
|服务端|
   :进行缓存处理;
endif
|客户端|
:显示天气状况;
stop
@enduml